name: Run Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: vendor/bin/phpunit
